### ISSUE TITLE
Cannot run WebMidi on recently released Node v21.1.0

### ISSUE THREAD

**Issue by nnirror** [djipco/webmidi#392]
**Description**

A user of a repository I maintain which includes the WebMIDI npm package reported [this issue](https://github.com/nnirror/facet/issues/75), which I have been able to duplicate locally.

I cannot run WebMIDI on Node v21.1.0, which was released several weeks ago. I did test that the issue does _not_ occur running Node v18.14.0, nor does it occur running v14.20.0.

So I suspect it must be specific to the very recently released node versions.

If I run the following `test.js` script:

`const {WebMidi} = require('webmidi');`

I get the following error:

```
TypeError: Cannot set property navigator of #<Object> which has only a getter
    at Object.<anonymous> (/Users/cella/Desktop/test/node_modules/webmidi/dist/cjs/webmidi.cjs.min.js:445:4390)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/cella/Desktop/test/test.js:1:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```

**Environment:**
Specify the environment where you are witnessing the problem:
  - The user who reported this to me was using Ubuntu 22.04, and I am running MacOS 10.15.2.
  - NodeJS version of WebMIDI
  - Node v21.1.0

**Details**
Thank you for your time! WebMIDI is amazing.

**Comment by djipco** [comment]
Version 3.1.7, which is available right now, fixes this problem. If you want to use Node.js v21+, you need to update.
